"""delete source_id

Revision ID: 40fb40cabe33
Revises: 
Create Date: 2025-07-10 09:13:05.350567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fb40cabe33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movements_source_id_fkey'), 'movements', type_='foreignkey')
    op.drop_column('movements', 'source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('movements_source_id_fkey'), 'movements', 'warehouses', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
